name: build applications
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
    paths:
      - applications/**
jobs:
  push:
    name: "applications:${{ matrix.application }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        application:
          - dashy
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./applications/${{ matrix.application }}
          file: ./applications/${{ matrix.application }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/pterodactyl/applications:${{ matrix.application }}